name: clean_arch
version: 1.0.0+1
publish_to: none
description: Clean Architecture useing Getx with firebase
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.20.0
  cloud_firestore: 3.4.2
  get_storage: 2.0.3
  firebase_auth: 3.6.1
  intl: 0.17.0
  uuid: 3.0.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

